### ISSUE TITLE
Can't use the plugin

### ISSUE THREAD

**Issue by cperezvinsite** [rodrigo-martinezd/cordova-dialog-gps#14]
Hi I try to install the plugin into my cordova project with : 
<code>cordova plugin add https://github.com/rodrigo-martinezd/cordova-dialog-gps.git</code>

After that, and the success of cordova I try to implement the code, but when I do 
<code>cordova.dialogGPS()</code>
I get the error
<code>TypeError: Object #<Object> has no method 'dialogGPS'</code>  
That's because cordova object has no dialogGPS on his structure, I don't know what to do.

If I run <code>cordova plugin list</code> 
I get this
<code>cl.rmd.cordova.dialoggps 0.0.2 "DialogGPS"</code> 
And in the folder of plugins there is the dialogs plugin

By the way, I'm using cordova 5
Regards

**Comment by rodrigo-md** [comment]
Hi, you're right. If the error is that the object haven't no method. Is because the cordova object doesn't have dialogGPS and this occurs for two posibles reasons.
1.  You're calling "cordova.dialogGPS()" before the  cordova object it's ready. it's for this that you must call inside a  wrapper that listen for 'ready' event of cordova.

```
document.addEventListener('deviceready' , function() { 
    cordova.dialogGPS();
});
```
1. The second possible reason is that in Cordova 5 has changed something I did not consider . I check the code to correct the error.

Please , try the first option and see if still does not work
